# Site settings
title: Ronald Hong's blog
email: ronniejhong@gmail.com
description: >
  Ronald Hong is a software developer currently living in Boston, MA.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://flushentitypacket.github.io/" # the base hostname & protocol for your site
# twitter_username:
github_username: flushentitypacket

# Build settings
markdown: kramdown
